import type { ApprovalRequest } from '@/types';
import { daysFromNow } from './date-seed';

const EXPENSE_STAGES = ['Manager Review', 'Finance Approval'];
const LEAVE_STAGES = ['Manager Review', 'HR Review'];
const PURCHASE_STAGES = ['Dept. Head Review', 'Procurement Review', 'Finance Approval'];
const GENERAL_STAGES = ['Manager Review', 'Finance Approval'];

export const approvals: ApprovalRequest[] = [
  {
    id: 'a_1',
    title: 'Client dinner — Meridian kickoff',
    description: 'Team dinner with the Meridian regional partner during the EMEA kickoff trip.',
    requesterId: 'u_walker',
    workflowTemplateId: 'wf_expense',
    type: 'Expense',
    priority: 'medium',
    status: 'pending',
    currentStage: 'Manager Review',
    stages: EXPENSE_STAGES,
    amount: 486,
    requestedAt: daysFromNow(-1),
    history: [
      { id: 'h1', actorId: 'u_walker', action: 'submitted', timestamp: daysFromNow(-1) },
    ],
  },
  {
    id: 'a_2',
    title: 'MacBook Pro 16" — new hire equipment',
    description: 'Standard equipment provisioning for incoming backend engineer.',
    requesterId: 'u_kim',
    workflowTemplateId: 'wf_purchase',
    type: 'Purchase',
    priority: 'high',
    status: 'pending',
    currentStage: 'Procurement Review',
    stages: PURCHASE_STAGES,
    amount: 2899,
    requestedAt: daysFromNow(-3),
    history: [
      { id: 'h1', actorId: 'u_kim', action: 'submitted', timestamp: daysFromNow(-3) },
      { id: 'h2', actorId: 'u_ade', action: 'approved', note: 'Approved — budget confirmed.', timestamp: daysFromNow(-2) },
    ],
  },
  {
    id: 'a_3',
    title: 'Annual leave — 8 days, December',
    description: 'End-of-year leave request covering Dec 22 – Dec 31.',
    requesterId: 'u_novak',
    workflowTemplateId: 'wf_leave',
    type: 'Leave',
    priority: 'low',
    status: 'pending',
    currentStage: 'HR Review',
    stages: LEAVE_STAGES,
    requestedAt: daysFromNow(-2),
    history: [
      { id: 'h1', actorId: 'u_novak', action: 'submitted', timestamp: daysFromNow(-2) },
      { id: 'h2', actorId: 'u_kim', action: 'approved', note: 'Coverage confirmed with the team.', timestamp: daysFromNow(-1) },
    ],
  },
  {
    id: 'a_4',
    title: 'Figma Enterprise seats — Design team',
    description: 'Upgrade to Figma Enterprise for the design org, 8 additional seats.',
    requesterId: 'u_okafor',
    workflowTemplateId: 'wf_purchase',
    type: 'Purchase',
    priority: 'medium',
    status: 'pending',
    currentStage: 'Dept. Head Review',
    stages: PURCHASE_STAGES,
    amount: 5760,
    requestedAt: daysFromNow(0),
    history: [
      { id: 'h1', actorId: 'u_okafor', action: 'submitted', timestamp: daysFromNow(0) },
    ],
  },
  {
    id: 'a_5',
    title: 'Conference travel — SaaS Summit Austin',
    description: 'Flights and hotel for two attendees at SaaS Summit.',
    requesterId: 'u_hassan',
    workflowTemplateId: 'wf_expense',
    type: 'Expense',
    priority: 'medium',
    status: 'pending',
    currentStage: 'Manager Review',
    stages: EXPENSE_STAGES,
    amount: 3140,
    requestedAt: daysFromNow(-1),
    history: [
      { id: 'h1', actorId: 'u_hassan', action: 'submitted', timestamp: daysFromNow(-1) },
    ],
  },
  {
    id: 'a_6',
    title: 'Contractor engagement — QA support',
    description: 'Six-week contract to support the Aurora release QA push.',
    requesterId: 'u_kim',
    workflowTemplateId: 'wf_general',
    type: 'General',
    priority: 'urgent',
    status: 'pending',
    currentStage: 'Finance Approval',
    stages: GENERAL_STAGES,
    amount: 14200,
    requestedAt: daysFromNow(-4),
    history: [
      { id: 'h1', actorId: 'u_kim', action: 'submitted', timestamp: daysFromNow(-4) },
      { id: 'h2', actorId: 'u_rivera', action: 'approved', note: 'Approved given release timeline.', timestamp: daysFromNow(-3) },
    ],
  },
  {
    id: 'a_7',
    title: 'Home office setup reimbursement',
    description: 'Monitor and ergonomic chair for remote workspace.',
    requesterId: 'u_ferreira',
    workflowTemplateId: 'wf_expense',
    type: 'Expense',
    priority: 'low',
    status: 'approved',
    currentStage: 'Finance Approval',
    stages: EXPENSE_STAGES,
    amount: 612,
    requestedAt: daysFromNow(-9),
    history: [
      { id: 'h1', actorId: 'u_ferreira', action: 'submitted', timestamp: daysFromNow(-9) },
      { id: 'h2', actorId: 'u_kim', action: 'approved', timestamp: daysFromNow(-8) },
      { id: 'h3', actorId: 'u_chen', action: 'approved', note: 'Within policy.', timestamp: daysFromNow(-6) },
    ],
  },
  {
    id: 'a_8',
    title: 'Annual leave — 3 days',
    description: 'Long weekend leave request.',
    requesterId: 'u_dubois',
    workflowTemplateId: 'wf_leave',
    type: 'Leave',
    priority: 'low',
    status: 'approved',
    currentStage: 'HR Review',
    stages: LEAVE_STAGES,
    requestedAt: daysFromNow(-6),
    history: [
      { id: 'h1', actorId: 'u_dubois', action: 'submitted', timestamp: daysFromNow(-6) },
      { id: 'h2', actorId: 'u_okafor', action: 'approved', timestamp: daysFromNow(-5) },
    ],
  },
  {
    id: 'a_9',
    title: 'Vendor renewal — analytics platform',
    description: 'Annual renewal of the product analytics subscription.',
    requesterId: 'u_martins',
    workflowTemplateId: 'wf_purchase',
    type: 'Purchase',
    priority: 'medium',
    status: 'approved',
    currentStage: 'Finance Approval',
    stages: PURCHASE_STAGES,
    amount: 18400,
    requestedAt: daysFromNow(-12),
    history: [
      { id: 'h1', actorId: 'u_martins', action: 'submitted', timestamp: daysFromNow(-12) },
      { id: 'h2', actorId: 'u_ade', action: 'approved', timestamp: daysFromNow(-10) },
      { id: 'h3', actorId: 'u_chen', action: 'approved', note: 'Renewal terms unchanged from last year.', timestamp: daysFromNow(-8) },
    ],
  },
  {
    id: 'a_10',
    title: 'Team offsite — Lisbon',
    description: 'Engineering team offsite, venue and travel budget.',
    requesterId: 'u_kim',
    workflowTemplateId: 'wf_general',
    type: 'General',
    priority: 'high',
    status: 'approved',
    currentStage: 'Finance Approval',
    stages: GENERAL_STAGES,
    amount: 9800,
    requestedAt: daysFromNow(-15),
    history: [
      { id: 'h1', actorId: 'u_kim', action: 'submitted', timestamp: daysFromNow(-15) },
      { id: 'h2', actorId: 'u_rivera', action: 'approved', timestamp: daysFromNow(-13) },
    ],
  },
  {
    id: 'a_11',
    title: 'Non-standard equipment — dual monitor arm',
    description: 'Outside standard equipment catalog, requires exception approval.',
    requesterId: 'u_patel',
    workflowTemplateId: 'wf_purchase',
    type: 'Purchase',
    priority: 'low',
    status: 'rejected',
    currentStage: 'Dept. Head Review',
    stages: PURCHASE_STAGES,
    amount: 340,
    requestedAt: daysFromNow(-10),
    history: [
      { id: 'h1', actorId: 'u_patel', action: 'submitted', timestamp: daysFromNow(-10) },
      { id: 'h2', actorId: 'u_kim', action: 'rejected', note: 'Please order from the approved equipment catalog instead.', timestamp: daysFromNow(-9) },
    ],
  },
  {
    id: 'a_12',
    title: 'Extended leave — 15 days',
    description: 'Extended personal leave request outside standard PTO cadence.',
    requesterId: 'u_johansson',
    workflowTemplateId: 'wf_leave',
    type: 'Leave',
    priority: 'medium',
    status: 'rejected',
    currentStage: 'HR Review',
    stages: LEAVE_STAGES,
    requestedAt: daysFromNow(-14),
    history: [
      { id: 'h1', actorId: 'u_johansson', action: 'submitted', timestamp: daysFromNow(-14) },
      { id: 'h2', actorId: 'u_okafor', action: 'approved', timestamp: daysFromNow(-13) },
      { id: 'h3', actorId: 'u_ade', action: 'rejected', note: 'Overlaps with Q4 close — please resubmit for January.', timestamp: daysFromNow(-11) },
    ],
  },
  {
    id: 'a_13',
    title: 'Travel budget increase — Sales team',
    description: 'Q4 travel budget increase for enterprise prospect visits.',
    requesterId: 'u_walker',
    workflowTemplateId: 'wf_general',
    type: 'General',
    priority: 'medium',
    status: 'changes-requested',
    currentStage: 'Manager Review',
    stages: GENERAL_STAGES,
    amount: 22000,
    requestedAt: daysFromNow(-5),
    history: [
      { id: 'h1', actorId: 'u_walker', action: 'submitted', timestamp: daysFromNow(-5) },
      { id: 'h2', actorId: 'u_ade', action: 'changes-requested', note: 'Break this down by account before resubmitting.', timestamp: daysFromNow(-4) },
    ],
  },
  {
    id: 'a_14',
    title: 'Software license — code review tool',
    description: 'Team-wide license for an automated code review tool.',
    requesterId: 'u_novak',
    workflowTemplateId: 'wf_purchase',
    type: 'Purchase',
    priority: 'medium',
    status: 'changes-requested',
    currentStage: 'Procurement Review',
    stages: PURCHASE_STAGES,
    amount: 4200,
    requestedAt: daysFromNow(-3),
    history: [
      { id: 'h1', actorId: 'u_novak', action: 'submitted', timestamp: daysFromNow(-3) },
      { id: 'h2', actorId: 'u_kim', action: 'approved', timestamp: daysFromNow(-2) },
      { id: 'h3', actorId: 'u_chen', action: 'changes-requested', note: 'Need a security review attached before finance can approve.', timestamp: daysFromNow(-1) },
    ],
  },
];

export function getApprovalById(id: string | null | undefined): ApprovalRequest | undefined {
  if (!id) return undefined;
  return approvals.find((approval) => approval.id === id);
}
