import type { Project } from '@/types';
import { daysFromNow } from './date-seed';

export const projects: Project[] = [
  {
    id: 'p_aurora',
    name: 'Project Aurora',
    description: 'Rebuild of the customer billing engine with usage-based pricing and real-time invoicing.',
    status: 'active',
    priority: 'high',
    health: 'on-track',
    ownerId: 'u_rivera',
    memberIds: ['u_rivera', 'u_novak', 'u_patel', 'u_kim'],
    startDate: daysFromNow(-64),
    deadline: daysFromNow(21),
    progress: 74,
    accent: '#CEA254',
    tags: ['Billing', 'Platform'],
    milestones: [
      { id: 'm1', title: 'Pricing engine spec', dueDate: daysFromNow(-40), completed: true },
      { id: 'm2', title: 'Usage metering pipeline', dueDate: daysFromNow(-12), completed: true },
      { id: 'm3', title: 'Invoice generation UI', dueDate: daysFromNow(6), completed: false },
      { id: 'm4', title: 'Migration & rollout', dueDate: daysFromNow(21), completed: false },
    ],
  },
  {
    id: 'p_meridian',
    name: 'Meridian Expansion',
    description: 'Market entry program covering EMEA localization, compliance review, and regional pricing.',
    status: 'active',
    priority: 'high',
    health: 'at-risk',
    ownerId: 'u_ade',
    memberIds: ['u_ade', 'u_walker', 'u_hassan', 'u_martins'],
    startDate: daysFromNow(-48),
    deadline: daysFromNow(9),
    progress: 52,
    accent: '#5C85E6',
    tags: ['Expansion', 'Compliance'],
    milestones: [
      { id: 'm1', title: 'Regulatory review', dueDate: daysFromNow(-20), completed: true },
      { id: 'm2', title: 'Localization pass', dueDate: daysFromNow(-3), completed: false },
      { id: 'm3', title: 'Regional pricing sign-off', dueDate: daysFromNow(9), completed: false },
    ],
  },
  {
    id: 'p_helios',
    name: 'Helios Design System',
    description: 'Unify design language and component library across all internal and customer-facing surfaces.',
    status: 'active',
    priority: 'medium',
    health: 'on-track',
    ownerId: 'u_okafor',
    memberIds: ['u_okafor', 'u_dubois', 'u_johansson'],
    startDate: daysFromNow(-90),
    deadline: daysFromNow(35),
    progress: 61,
    accent: '#3FA87D',
    tags: ['Design System', 'Frontend'],
    milestones: [
      { id: 'm1', title: 'Token architecture', dueDate: daysFromNow(-70), completed: true },
      { id: 'm2', title: 'Core component audit', dueDate: daysFromNow(-30), completed: true },
      { id: 'm3', title: 'Documentation site', dueDate: daysFromNow(15), completed: false },
      { id: 'm4', title: 'Team-wide adoption', dueDate: daysFromNow(35), completed: false },
    ],
  },
  {
    id: 'p_northwind',
    name: 'Northwind Integration',
    description: 'Connect Aureon with Northwind ERP for two-way sync of purchase orders and vendor records.',
    status: 'planning',
    priority: 'medium',
    health: 'on-track',
    ownerId: 'u_kim',
    memberIds: ['u_kim', 'u_patel', 'u_ferreira'],
    startDate: daysFromNow(-8),
    deadline: daysFromNow(58),
    progress: 14,
    accent: '#DD9A3F',
    tags: ['Integration', 'ERP'],
    milestones: [
      { id: 'm1', title: 'API contract review', dueDate: daysFromNow(4), completed: false },
      { id: 'm2', title: 'Sandbox integration', dueDate: daysFromNow(28), completed: false },
      { id: 'm3', title: 'Production cutover', dueDate: daysFromNow(58), completed: false },
    ],
  },
  {
    id: 'p_beacon',
    name: 'Beacon Onboarding Revamp',
    description: 'Redesign the new-customer onboarding flow to cut time-to-value from 14 days to under 5.',
    status: 'active',
    priority: 'urgent',
    health: 'at-risk',
    ownerId: 'u_larsson',
    memberIds: ['u_larsson', 'u_dubois', 'u_walker'],
    startDate: daysFromNow(-30),
    deadline: daysFromNow(4),
    progress: 68,
    accent: '#DC5555',
    tags: ['Onboarding', 'Customer Success'],
    milestones: [
      { id: 'm1', title: 'Journey mapping', dueDate: daysFromNow(-22), completed: true },
      { id: 'm2', title: 'Guided setup flow', dueDate: daysFromNow(-2), completed: true },
      { id: 'm3', title: 'Success metrics dashboard', dueDate: daysFromNow(4), completed: false },
    ],
  },
  {
    id: 'p_catalyst',
    name: 'Catalyst Automation Suite',
    description: 'Internal workflow automation for procurement, reimbursements, and vendor approvals.',
    status: 'completed',
    priority: 'medium',
    health: 'on-track',
    ownerId: 'u_chen',
    memberIds: ['u_chen', 'u_martins', 'u_ade'],
    startDate: daysFromNow(-140),
    deadline: daysFromNow(-14),
    progress: 100,
    accent: '#8A7CC7',
    tags: ['Automation', 'Finance'],
    milestones: [
      { id: 'm1', title: 'Workflow templates', dueDate: daysFromNow(-100), completed: true },
      { id: 'm2', title: 'Approval routing engine', dueDate: daysFromNow(-55), completed: true },
      { id: 'm3', title: 'Org-wide rollout', dueDate: daysFromNow(-14), completed: true },
    ],
  },
  {
    id: 'p_solstice',
    name: 'Solstice Data Migration',
    description: 'Migrate legacy reporting infrastructure to the new analytics warehouse.',
    status: 'on-hold',
    priority: 'low',
    health: 'off-track',
    ownerId: 'u_kim',
    memberIds: ['u_kim', 'u_novak'],
    startDate: daysFromNow(-20),
    deadline: daysFromNow(70),
    progress: 22,
    accent: '#4FA8C0',
    tags: ['Data', 'Infrastructure'],
    milestones: [
      { id: 'm1', title: 'Schema mapping', dueDate: daysFromNow(-5), completed: true },
      { id: 'm2', title: 'Pipeline dry run', dueDate: daysFromNow(30), completed: false },
    ],
  },
];

export function getProjectById(id: string | null | undefined): Project | undefined {
  if (!id) return undefined;
  return projects.find((project) => project.id === id);
}
