import type { User } from '@/types';

export const AVATAR_COLORS = [
  '#CEA254', // gold
  '#5C85E6', // slate blue
  '#3FA87D', // emerald
  '#DC5555', // rose
  '#8A7CC7', // violet
  '#4FA8C0', // teal
  '#DD9A3F', // amber
  '#C0688C', // mauve
] as const;

export const CURRENT_USER_ID = 'u_rivera';

export const users: User[] = [
  {
    id: 'u_rivera',
    name: 'Alex Rivera',
    email: 'alex.rivera@aureon.io',
    role: 'administrator',
    title: 'Head of Product',
    department: 'Product',
    color: AVATAR_COLORS[0],
    activeTasks: 7,
    completedTasks: 142,
    workload: 78,
    timezone: 'PST',
    joinedAt: '2022-03-14',
  },
  {
    id: 'u_okafor',
    name: 'Sarah Okafor',
    email: 'sarah.okafor@aureon.io',
    role: 'manager',
    title: 'Design Lead',
    department: 'Design',
    color: AVATAR_COLORS[3],
    activeTasks: 5,
    completedTasks: 98,
    workload: 64,
    timezone: 'EST',
    joinedAt: '2022-06-02',
  },
  {
    id: 'u_chen',
    name: 'Michael Chen',
    email: 'michael.chen@aureon.io',
    role: 'manager',
    title: 'Finance Manager',
    department: 'Finance',
    color: AVATAR_COLORS[1],
    activeTasks: 4,
    completedTasks: 76,
    workload: 55,
    timezone: 'PST',
    joinedAt: '2021-11-20',
  },
  {
    id: 'u_novak',
    name: 'Elena Novak',
    email: 'elena.novak@aureon.io',
    role: 'member',
    title: 'Senior Engineer',
    department: 'Engineering',
    color: AVATAR_COLORS[2],
    activeTasks: 9,
    completedTasks: 211,
    workload: 91,
    timezone: 'CET',
    joinedAt: '2021-05-09',
  },
  {
    id: 'u_patel',
    name: 'Rohan Patel',
    email: 'rohan.patel@aureon.io',
    role: 'member',
    title: 'Backend Engineer',
    department: 'Engineering',
    color: AVATAR_COLORS[4],
    activeTasks: 6,
    completedTasks: 133,
    workload: 82,
    timezone: 'IST',
    joinedAt: '2023-01-16',
  },
  {
    id: 'u_dubois',
    name: 'Claire Dubois',
    email: 'claire.dubois@aureon.io',
    role: 'member',
    title: 'Product Designer',
    department: 'Design',
    color: AVATAR_COLORS[5],
    activeTasks: 5,
    completedTasks: 87,
    workload: 68,
    timezone: 'CET',
    joinedAt: '2022-09-11',
  },
  {
    id: 'u_martins',
    name: 'Diego Martins',
    email: 'diego.martins@aureon.io',
    role: 'member',
    title: 'Operations Analyst',
    department: 'Operations',
    color: AVATAR_COLORS[6],
    activeTasks: 3,
    completedTasks: 59,
    workload: 41,
    timezone: 'BRT',
    joinedAt: '2023-04-03',
  },
  {
    id: 'u_kim',
    name: 'Jenny Kim',
    email: 'jenny.kim@aureon.io',
    role: 'manager',
    title: 'Engineering Manager',
    department: 'Engineering',
    color: AVATAR_COLORS[7],
    activeTasks: 4,
    completedTasks: 156,
    workload: 73,
    timezone: 'PST',
    joinedAt: '2021-02-27',
  },
  {
    id: 'u_hassan',
    name: 'Omar Hassan',
    email: 'omar.hassan@aureon.io',
    role: 'member',
    title: 'Marketing Lead',
    department: 'Marketing',
    color: AVATAR_COLORS[1],
    activeTasks: 6,
    completedTasks: 64,
    workload: 59,
    timezone: 'GST',
    joinedAt: '2023-07-19',
  },
  {
    id: 'u_larsson',
    name: 'Ingrid Larsson',
    email: 'ingrid.larsson@aureon.io',
    role: 'member',
    title: 'Customer Success Lead',
    department: 'Customer Success',
    color: AVATAR_COLORS[2],
    activeTasks: 8,
    completedTasks: 121,
    workload: 87,
    timezone: 'CET',
    joinedAt: '2022-01-30',
  },
  {
    id: 'u_walker',
    name: 'Priya Walker',
    email: 'priya.walker@aureon.io',
    role: 'member',
    title: 'Sales Director',
    department: 'Sales',
    color: AVATAR_COLORS[3],
    activeTasks: 5,
    completedTasks: 93,
    workload: 62,
    timezone: 'EST',
    joinedAt: '2022-08-08',
  },
  {
    id: 'u_ferreira',
    name: 'Lucas Ferreira',
    email: 'lucas.ferreira@aureon.io',
    role: 'member',
    title: 'QA Engineer',
    department: 'Engineering',
    color: AVATAR_COLORS[4],
    activeTasks: 7,
    completedTasks: 104,
    workload: 76,
    timezone: 'BRT',
    joinedAt: '2023-02-14',
  },
  {
    id: 'u_johansson',
    name: 'Freya Johansson',
    email: 'freya.johansson@aureon.io',
    role: 'member',
    title: 'Content Strategist',
    department: 'Marketing',
    color: AVATAR_COLORS[5],
    activeTasks: 3,
    completedTasks: 47,
    workload: 38,
    timezone: 'CET',
    joinedAt: '2023-10-02',
  },
  {
    id: 'u_ade',
    name: 'Tunde Ade',
    email: 'tunde.ade@aureon.io',
    role: 'manager',
    title: 'Operations Director',
    department: 'Operations',
    color: AVATAR_COLORS[6],
    activeTasks: 4,
    completedTasks: 168,
    workload: 70,
    timezone: 'GST',
    joinedAt: '2021-07-05',
  },
];

export function getUserById(id: string | null | undefined): User | undefined {
  if (!id) return undefined;
  return users.find((user) => user.id === id);
}
